### ISSUE TITLE
The Example Output

### ISSUE THREAD

**Issue by suntong** [mewspring/dot-old#1]
The [Example Output](https://godoc.org/github.com/mewspring/dot#example-Read) is now different, right? Since fix 5792637 Print nodes before edges in Graph.String, right?

**Comment by suntong** [comment]
Confirmed. Ref:
https://github.com/suntong/lang/blob/master/lang/Go/src/graph/DotDemo1.go

**Comment by mewmew** [comment]
This issue was moved to mewspring/dot#1
