### ISSUE TITLE
Add more encapsulations

### ISSUE THREAD

**Issue by suntong** [mewspring/dot-old#2]
I need to access the [Edge internal data](https://github.com/mewspring/dot/blob/master/edges.go#L30-L34):

```go
type Edges struct {
	SrcToDsts map[string]map[string]*Edge
	DstToSrcs map[string]map[string]*Edge
	Edges     []*Edge
}
```

but I don't want to dip directly into the above data structure, but would like to access them through encapsulations instead. So, I'd like to propose the following access methods:

```
// EdgesToParents returns all the edges linked to its parents of the given nodeName.
EdgesToParents(nodeName string) map[string]... => return DstToSrcs[nodeName]

// EdgesToChildren returns all the edges linked to its children of the given nodeName.
EdgesToChildren(nodeName string) map[string]... => return SrcToDsts[nodeName]

```
Or something similar. Would that be OK? I don't mind patch myself and send in the pull request. 

Moreover, please provide the access method of `NodesAll` for all the nodes within the given Graph:

```
// NodesAll returns all the nodes within the given Graph.
```

As I need access to that info as well. Would that be OK?

Thanks

**Comment by mewmew** [comment]
This issue was moved to mewspring/dot#2
