### ISSUE TITLE
PANIC when building dominator tree and syntax error

### ISSUE THREAD

**Issue by suntong** [mewspring/dot-old#3]
Please take a look at the simple code [dotu.go](https://github.com/suntong/lang/blob/master/lang/Go/src/graph/dotu.go)

It has the following problems,

- It will give the "`### PANIC ### when building dominator tree for`" error during execution. 
- The graph was output twice
- The graph will give the "`Error: syntax error in line 2 near '('`" error when processed with `dot`

This is how I run it:

```
$ go run dotu.go > /tmp/dcg-1.dot 2> /tmp/dcg-2.dot

$ cat /tmp/dcg-2.dot
2016/07/02 09:32:33 ### PANIC ### when building dominator tree for:

$ dot -Tpng /tmp/dcg-1.dot > /tmp/dcg-dn.png
Error: /tmp/dcg-1.dot: syntax error in line 2 near '('
```

I believe the third problem can be fixed if the output nodes are output in quotes.

**Comment by mewmew** [comment]
This issue was moved to mewspring/dot#3
